In [1]:
#Vektor Horiontal
import numpy as np
a = [1,2,3]
vektor1 = np.array(a)
print(vektor1)

[1 2 3]


In [2]:
# Vektor Vertikal
import numpy as np

b = [[1],[2],[3]]
vektor2 = np.array(b)
print(vektor2)

[[1]
 [2]
 [3]]


In [4]:
# Penjumlahan Vektor
import numpy as np

c = [[1],[2],[3]]
d = [[-1],[2],[10]]
vektor3 = np.array(c) + np.array(d)
print(vektor3)

[[ 0]
 [ 4]
 [13]]


In [5]:
# Pengurangan Vektor
import numpy as np

c = [[1],[2],[3]]
d = [[-1],[2],[10]]
vektor3 = np.array(c) - np.array(d)
print(vektor3)

[[ 2]
 [ 0]
 [-7]]


In [6]:
# Append Vektor
import numpy as np

c = [[1],[2],[3]]
d = [[-1],[2],[10]]
vektor3 = np.array(c+d)
print(vektor3)

[[ 1]
 [ 2]
 [ 3]
 [-1]
 [ 2]
 [10]]
